# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Anomalies2Contours
                                 A QGIS plugin
 This plugin converts statistical anomalies into contours based on custom parameters.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-28
        copyright            : (C) 2025 by Marhes S. & Hudak V.
        email                : sergemarhes@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Anomalies2Contours class from file Anomalies2Contours.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .anomalies2contours import Anomalies2Contours
    return Anomalies2Contours(iface)
